///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Propertyzar_Project
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("8a9ac45f-e870-4327-b4c3-a6d91e6e8e05", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Propertyzar_ProjectRepository repository.
        /// </summary>
        public static Propertyzar_ProjectRepository repo = Propertyzar_ProjectRepository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
            varChrome = "Chrome";
            VarBrowser = "Chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

        string _varChrome;

        /// <summary>
        /// Gets or sets the value of variable varChrome.
        /// </summary>
        [TestVariable("1fa50fcb-2a8e-4f5a-9221-d5f96ab56313")]
        public string varChrome
        {
            get { return _varChrome; }
            set { _varChrome = value; }
        }

        string _VarBrowser;

        /// <summary>
        /// Gets or sets the value of variable VarBrowser.
        /// </summary>
        [TestVariable("52891b35-dcdd-4a32-b5f3-b4af9091b0c1")]
        public string VarBrowser
        {
            get { return _VarBrowser; }
            set { _VarBrowser = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://pz-portal.icaniotech.com/en/auth/login' with browser specified by variable $VarBrowser in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://pz-portal.icaniotech.com/en/auth/login", VarBrowser, "", false, false, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
