///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Propertyzar_Project
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Propertyzar_ProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("cd3f0cc1-cc79-4f47-97c6-7ec478faac2f")]
    public partial class Propertyzar_ProjectRepository : RepoGenBaseFolder
    {
        static Propertyzar_ProjectRepository instance = new Propertyzar_ProjectRepository();
        Propertyzar_ProjectRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Propertyzar_ProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("cd3f0cc1-cc79-4f47-97c6-7ec478faac2f")]
        public static Propertyzar_ProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Propertyzar_ProjectRepository() 
            : base("Propertyzar_ProjectRepository", "/", null, 0, false, "cd3f0cc1-cc79-4f47-97c6-7ec478faac2f", ".\\RepositoryImages\\Propertyzar_ProjectRepositorycd3f0cc1.rximgres")
        {
            _applicationundertest = new Propertyzar_ProjectRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cd3f0cc1-cc79-4f47-97c6-7ec478faac2f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("70f0803c-4e6d-412d-822d-91e9f6f5d38f")]
        public virtual Propertyzar_ProjectRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Propertyzar_ProjectRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("70f0803c-4e6d-412d-822d-91e9f6f5d38f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailidInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _passwordlabelInfo;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='pz-portal.icaniotech.com']", parentFolder, 30000, null, false, "70f0803c-4e6d-412d-822d-91e9f6f5d38f", "")
            {
                _emailidInfo = new RepoItemInfo(this, "EmailId", ".//input[#'emailId']", ".//input[#'emailId']", 30000, null, "0950517b-c083-4256-bb71-654cd52ce3ec");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", ".//input[#'password']", 30000, null, "2857e139-9bef-4785-b86d-01568dcd3259");
                _passwordlabelInfo = new RepoItemInfo(this, "PasswordLabel", ".//label[#'password-label']", ".//label[#'password-label']", 30000, null, "2a2033e7-8e9b-4153-bcf3-a4bf5a532810");
                _loginInfo = new RepoItemInfo(this, "Login", "body/div[1]/?/?/form[@action='https://pz-portal.icaniotech.com/en/auth/login']/div/div[7]/?/?/button[@innertext='Login']", ".//button[@innertext='Login']", 30000, null, "1269849e-a0c7-4b0e-86ae-a1b470ef416f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("70f0803c-4e6d-412d-822d-91e9f6f5d38f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("70f0803c-4e6d-412d-822d-91e9f6f5d38f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailId item.
            /// </summary>
            [RepositoryItem("0950517b-c083-4256-bb71-654cd52ce3ec")]
            public virtual Ranorex.InputTag EmailId
            {
                get
                {
                    return _emailidInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EmailId item info.
            /// </summary>
            [RepositoryItemInfo("0950517b-c083-4256-bb71-654cd52ce3ec")]
            public virtual RepoItemInfo EmailIdInfo
            {
                get
                {
                    return _emailidInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("2857e139-9bef-4785-b86d-01568dcd3259")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("2857e139-9bef-4785-b86d-01568dcd3259")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The PasswordLabel item.
            /// </summary>
            [RepositoryItem("2a2033e7-8e9b-4153-bcf3-a4bf5a532810")]
            public virtual Ranorex.LabelTag PasswordLabel
            {
                get
                {
                    return _passwordlabelInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The PasswordLabel item info.
            /// </summary>
            [RepositoryItemInfo("2a2033e7-8e9b-4153-bcf3-a4bf5a532810")]
            public virtual RepoItemInfo PasswordLabelInfo
            {
                get
                {
                    return _passwordlabelInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("1269849e-a0c7-4b0e-86ae-a1b470ef416f")]
            public virtual Ranorex.ButtonTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("1269849e-a0c7-4b0e-86ae-a1b470ef416f")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
