///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Propertyzar_Project
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("6646d2ff-8eef-49ea-9458-db961b66184d", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Propertyzar_ProjectRepository repository.
        /// </summary>
        public static Propertyzar_ProjectRepository repo = Propertyzar_ProjectRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EmailId' at 69;18.", repo.ApplicationUnderTest.EmailIdInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.EmailId.Click("69;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EmailId' at 69;18.", repo.ApplicationUnderTest.EmailIdInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.EmailId.Click("69;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'sowm' with focus on 'ApplicationUnderTest.EmailId'.", repo.ApplicationUnderTest.EmailIdInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.EmailId.PressKeys("sowm");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'i09{LShiftKey down}@{LShiftKey up}yopmail.com' with focus on 'ApplicationUnderTest.EmailId'.", repo.ApplicationUnderTest.EmailIdInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.EmailId.PressKeys("i09{LShiftKey down}@{LShiftKey up}yopmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Password' at 84;19.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Password.Click("84;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PasswordLabel' at 70;28.", repo.ApplicationUnderTest.PasswordLabelInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.PasswordLabel.Click("70;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.Password' at 169;33.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Password.DoubleClick("169;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test{LShiftKey down}{@ down}{LShiftKey up}123456' with focus on 'ApplicationUnderTest.Password'.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Password.PressKeys("Test{LShiftKey down}{@ down}{LShiftKey up}123456");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Login' at 59;28.", repo.ApplicationUnderTest.LoginInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Login.Click("59;28");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
